In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression,Ridge,Lasso,RidgeCV,LarsCV,ElasticNet,ElasticNetCV
from sklearn.model_selection import train_test_split
import statsmodels.api as sm
import matplotlib.pyplot as plt
import seaborn as sns
from ydata_profiling import ProfileReport
import pickle

In [2]:
df = pd.read_csv('C:\\Users\\SrihariS\Admission_Predict.csv')

In [3]:
df.isnull().sum()

Serial No.           0
GRE Score            0
TOEFL Score          0
University Rating    0
SOP                  0
LOR                  0
CGPA                 0
Research             0
Chance of Admit      0
dtype: int64

In [4]:
pr = ProfileReport(df)

In [5]:
pr.to_widgets()

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render widgets:   0%|          | 0/1 [00:00<?, ?it/s]

In [6]:
df.drop(columns=['Serial No.'],inplace=True)

In [7]:
df

GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  Research  \
0          337          118                  4  4.5   4.5  9.65         1   
1          324          107                  4  4.0   4.5  8.87         1   
2          316          104                  3  3.0   3.5  8.00         1   
3          322          110                  3  3.5   2.5  8.67         1   
4          314          103                  2  2.0   3.0  8.21         0   
..         ...          ...                ...  ...   ...   ...       ...   
395        324          110                  3  3.5   3.5  9.04         1   
396        325          107                  3  3.0   3.5  9.11         1   
397        330          116                  4  5.0   4.5  9.45         1   
398        312          103                  3  3.5   4.0  8.78         0   
399        333          117                  4  5.0   4.0  9.66         1   

     Chance of Admit   
0                0.92  
1                0.76  
2                0.72  
3                0.80  
4                0.65  
..                ...  
395              0.82  
396              0.84  
397              0.91  
398              0.67  
399              0.95  

[400 rows x 8 columns]

In [8]:
#df[]=df[].fillna(df[].mean())

In [9]:
y = df['Chance of Admit ']

In [10]:
df

GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  Research  \
0          337          118                  4  4.5   4.5  9.65         1   
1          324          107                  4  4.0   4.5  8.87         1   
2          316          104                  3  3.0   3.5  8.00         1   
3          322          110                  3  3.5   2.5  8.67         1   
4          314          103                  2  2.0   3.0  8.21         0   
..         ...          ...                ...  ...   ...   ...       ...   
395        324          110                  3  3.5   3.5  9.04         1   
396        325          107                  3  3.0   3.5  9.11         1   
397        330          116                  4  5.0   4.5  9.45         1   
398        312          103                  3  3.5   4.0  8.78         0   
399        333          117                  4  5.0   4.0  9.66         1   

     Chance of Admit   
0                0.92  
1                0.76  
2                0.72  
3                0.80  
4                0.65  
..                ...  
395              0.82  
396              0.84  
397              0.91  
398              0.67  
399              0.95  

[400 rows x 8 columns]

In [11]:
x = df.iloc[:,:7]

In [12]:
x

GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  Research
0          337          118                  4  4.5   4.5  9.65         1
1          324          107                  4  4.0   4.5  8.87         1
2          316          104                  3  3.0   3.5  8.00         1
3          322          110                  3  3.5   2.5  8.67         1
4          314          103                  2  2.0   3.0  8.21         0
..         ...          ...                ...  ...   ...   ...       ...
395        324          110                  3  3.5   3.5  9.04         1
396        325          107                  3  3.0   3.5  9.11         1
397        330          116                  4  5.0   4.5  9.45         1
398        312          103                  3  3.5   4.0  8.78         0
399        333          117                  4  5.0   4.0  9.66         1

[400 rows x 7 columns]

In [13]:
scalar = StandardScaler()

In [14]:
arr = scalar.fit_transform(x)

In [15]:
arr

array([[ 1.76210664,  1.74697064,  0.79882862, ...,  1.16732114,
         1.76481828,  0.90911166],
       [ 0.62765641, -0.06763531,  0.79882862, ...,  1.16732114,
         0.45515126,  0.90911166],
       [-0.07046681, -0.56252785, -0.07660001, ...,  0.05293342,
        -1.00563118,  0.90911166],
       ...,
       [ 1.15124883,  1.41704229,  0.79882862, ...,  1.16732114,
         1.42900622,  0.90911166],
       [-0.41952842, -0.72749202, -0.07660001, ...,  0.61012728,
         0.30403584, -1.09997489],
       [ 1.41304503,  1.58200646,  0.79882862, ...,  0.61012728,
         1.78160888,  0.90911166]])

In [16]:
df1 = pd.DataFrame(arr)

In [17]:
df1

0         1         2         3         4         5         6
0    1.762107  1.746971  0.798829  1.093864  1.167321  1.764818  0.909112
1    0.627656 -0.067635  0.798829  0.596653  1.167321  0.455151  0.909112
2   -0.070467 -0.562528 -0.076600 -0.397769  0.052933 -1.005631  0.909112
3    0.453126  0.427257 -0.076600  0.099442 -1.061454  0.119339  0.909112
4   -0.244998 -0.727492 -0.952029 -1.392191 -0.504260 -0.653029 -1.099975
..        ...       ...       ...       ...       ...       ...       ...
395  0.627656  0.427257 -0.076600  0.099442  0.052933  0.740592  0.909112
396  0.714922 -0.067635 -0.076600 -0.397769  0.052933  0.858126  0.909112
397  1.151249  1.417042  0.798829  1.591075  1.167321  1.429006  0.909112
398 -0.419528 -0.727492 -0.076600  0.099442  0.610127  0.304036 -1.099975
399  1.413045  1.582006  0.798829  1.591075  0.610127  1.781609  0.909112

[400 rows x 7 columns]

In [18]:
pa = ProfileReport(df1)

In [19]:
pa.to_widgets()

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render widgets:   0%|          | 0/1 [00:00<?, ?it/s]

In [20]:
from statsmodels.stats.outliers_influence import variance_inflation_factor

In [21]:
arr.shape

(400, 7)

In [22]:
arr.shape[1]

7

In [23]:
vif_df=pd.DataFrame()

In [24]:
vif_df['vif'] = [variance_inflation_factor(arr,i) for i in range(arr.shape[1])]

In [25]:
vif_df['feature'] = x.columns

In [26]:
vif_df

vif            feature
0  4.615516          GRE Score
1  4.288959        TOEFL Score
2  2.919606  University Rating
3  3.075504                SOP
4  2.431258               LOR 
5  5.207403               CGPA
6  1.543312           Research

In [27]:
x_train,x_test,y_train,y_test = train_test_split(arr,y,test_size=0.25,random_state=30)

In [28]:
x_test

array([[ 0.2785948 ,  0.42725722,  1.67425725,  1.59107523,  1.724515  ,
         1.00924116,  0.90911166],
       [-1.64124406, -1.05742038, -0.95202863, -1.88940184, -1.61864817,
        -1.24069961, -1.09997489],
       [ 0.01679859,  0.42725722, -0.07660001,  0.59665321,  1.16732114,
         0.85812573,  0.90911166],
       [-0.24499762, -0.23259949, -0.07660001, -0.39776881,  1.724515  ,
         0.50552307, -1.09997489],
       [-0.59405923, -0.06763531, -0.07660001,  0.0994422 ,  0.05293342,
         0.11933921, -1.09997489],
       [ 1.32577963,  1.74697064,  1.67425725,  1.59107523,  1.724515  ,
         1.46258743,  0.90911166],
       [ 0.80218721,  0.5922214 ,  1.67425725,  1.09386422,  0.61012728,
         1.05961296,  0.90911166],
       [ 1.23851423,  1.91193482,  0.79882862,  1.59107523,  1.16732114,
         1.24430959,  0.90911166],
       [-0.33226302, -0.72749202, -0.07660001,  0.59665321,  0.61012728,
         0.25366403, -1.09997489],
       [-0.41952842,  0.2622

In [29]:
x_train,x_test,y_train,y_test = train_test_split(df1,y,test_size=0.10,random_state=30)

In [30]:
lm = LinearRegression()

In [31]:
lm = lm.fit(x_train,y_train)

In [32]:
lm.predict([[0.2785948 ,  0.42725722,  1.67425725,  1.59107523,  1.724515  ,
         1.00924116,  0.90911166]])

C:\Users\SrihariS\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([0.86185491])

In [33]:
lm.score(x_test,y_test)

0.8861330916197688

In [34]:
save_model = pickle.dump(lm,open('admission.pickle','wb'))

In [35]:
model = pickle.load(open('admission.pickle','rb'))

In [36]:
model.score(x_test,y_test)

0.8861330916197688

In [37]:
model.predict([[0.2785948 ,  0.42725722,  1.67425725,  1.59107523,  1.724515  ,
         1.00924116,  0.90911166]])

C:\Users\SrihariS\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([0.86185491])

In [38]:
model.predict([[337,118,4,4.5,4.5,9.65,1]])

C:\Users\SrihariS\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([10.3493055])

In [39]:
x = scalar.transform([[337,118,4,4.5,4.5,9.65,1]])

C:\Users\SrihariS\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [40]:
x

array([[1.76210664, 1.74697064, 0.79882862, 1.09386422, 1.16732114,
        1.76481828, 0.90911166]])

In [41]:
model.predict(x)

C:\Users\SrihariS\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([0.95079604])

In [42]:
model.predict([[1.762107,1.746971,0.798829,1.093864,1.167321,1.764818,0.909112]])

C:\Users\SrihariS\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([0.95079603])

In [43]:
model.coef_

array([ 0.02071005,  0.01564234,  0.00608509, -0.00277406,  0.02106769,
        0.07049004,  0.01295248])

In [44]:
model.intercept_

0.724379390425144

In [45]:
def adj_R(x,y):
    n = x.shape[0]
    p = x.shape[1]
    r2 = lm.score(x,y)
    formula = 1-(1-r2)*(n-1)/(n-p-1) 
    return formula

In [46]:
adj_R(x_test,y_test)

0.8612247054115932

In [47]:
lm.score(x_test,y_test)

0.8861330916197688

In [48]:
lassocv = LarsCV(cv =10,max_iter=2000,normalize=True)

In [49]:
lassocv.fit(x_train,y_train)

C:\Users\SrihariS\anaconda3\Lib\site-packages\sklearn\linear_model\_base.py:114: FutureWarning: 'normalize' was deprecated in version 1.2 and will be removed in 1.4.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), LarsCV())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)


  warnings.warn(


LarsCV(cv=10, max_iter=2000, normalize=True)

In [50]:
lassocv.alpha_

4.7888272568765274e-05

In [51]:
lasso=Lasso(lassocv.alpha_)


In [52]:
lasso.fit(x_train,y_train)

Lasso(alpha=4.7888272568765274e-05)

In [53]:
lasso.score(x_test,y_test)

0.8860944743324984

In [54]:
model.score(x_test,y_test)

0.8861330916197688

In [238]:
ridgecv = RidgeCV(cv =100)
ridgecv.fit(x_train,y_train)

RidgeCV(cv=100)

In [230]:
ridgecv.alpha_

10.0

In [234]:
ridge=Ridge(ridgecv.alpha_)
ridge.fit(x_train,y_train)

Ridge(alpha=10.0)

In [235]:
ridge.score(x_test,y_test)

0.8854903527002986

In [248]:
elasticv =ElasticNetCV(cv=10,alphas=None).fit(x_train,y_train)

In [250]:
elasticv.l1_ratio_

0.5

In [252]:
elasticv.alpha_

0.0017231757637832486

In [251]:
elasticv.score(x_test,y_test)

0.8856675546651113

In [255]:
elastic = ElasticNet(alpha=elasticv.alpha_,l1_ratio=elasticv.l1_ratio_).fit(x_train,y_train)

In [256]:
elastic.score(x_test,y_test)

0.8856675546651113